### ISSUE TITLE
Add an option for changing background color of card

### ISSUE THREAD

**Issue by codebeige** [bhauman/devcards#44]
When styling a component outside of its original context it is often desirable to do it against a appropriate background color. In such cases it would be great to allow setting the background of the actual card as an option like so:

``` clojure
(devcard white-thingy
"I need a dark surrounding"
(sab/html [:div {:style {:background "#fff"}} "Can you see my background?"])
{}
{:background "#333"})
```

**Comment by bhauman** [comment]
I'm thinking that adding a :classname option is a good way to go here.  

But just so you know you can color of the background for a whole namespace like this:

```css
.your_munged-name_space .com-rigsomelight-devcards_rendered-card {
  background-color: black;
}
```
I think that is enough specificity.
