### ISSUE TITLE
responsive CSS question regarding inline code samples in devcard

### ISSUE THREAD

**Issue by frankhale** [bhauman/devcards#51]
When the browser window is resized to 1000px or smaller this style is applied to code samples in a devcard. I find this visually jarring because the code samples are stretched to browser edges while everything else flows naturally. Is this CSS intentional? 

```css
@media (max-width: 1000px) {
 .com-rigsomelight-devcards-card-hide-border 
 .com-rigsomelight-devcards_rendered-card 
 .com-rigsomelight-devcards-markdown pre {
    margin-right: -3000px;
    margin-left: -3000px;
    padding-right: 3000px;
    padding-left: 3000px;
 }
}
```
