### ISSUE TITLE
Devcards styling overwrites my own

### ISSUE THREAD

**Issue by magnars** [bhauman/devcards#57]
Using Devcards is great. It feels like I'm writing a suite of visual tests, giving me that old TDD cycle of endorphins. :) The issue I'm having tho, is that the styles bundled with devcards overwrite my own - in particular font-size and font-face inside the cards.

It is certainly very useful to have nice looking devcards right out of the box. But it interferes with my ability to properly test how my own CSS interacts with my components.

One solution could be adding a flag that disables styling (colors, fonts), but keeps the layout.

Thoughts?

**Comment by bhauman** [comment]
Here's the relevant docs:
http://rigsomelight.com/devcards/#!/devdemos.css_opt_out

**Comment by magnars** [comment]
Of course you already thought about it. Brilliant! :-)

**Comment by magnars** [comment]
Hi!

What are your thought on moving styles like these to addons?

```css
.com-rigsomelight-devcards-base h1,
.com-rigsomelight-devcards-base h2,
.com-rigsomelight-devcards-base h3,
.com-rigsomelight-devcards-base h4,
.com-rigsomelight-devcards-base h5 {
    font-weight: 500;
}
```

and 

```css
.com-rigsomelight-devcards-base a {
    color: #428bca;
    text-decoration: none;
}
```

since they hit the content inside of a card?
